name: pips
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - Flask==3.0.0
    - flask-cors>=4.0.0
    - Werkzeug==3.0.1
    - BeautifulSoup4==4.12.2
    - Requests==2.31.0
    - python-dotenv==1.0.0
